name: pages

on:
  push:
    branches:
      - main

jobs:
  deploy_demo:
    runs-on: ubuntu-latest
    env:
      BASE_PATH: /blendic-svg/
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - run: yarn install
      - run: yarn docs:build
      - name: Deploy Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/.vitepress/dist
